### PR TITLE
Allow to configure SVGo options

### PR DESCRIPTION
**Pull request by mrleblanc101**

### CODE REVIEW

**Comment by mrleblanc101** [comment]
@sam3d Could you please look into this when you have some time ?

**Comment by manuelodelain** [comment]
Thanks @mrleblanc101 for the PR! 
As the `svgo` option is used only by the vue-svg-loader I think it should be nested into another level of option, for example: 
```
{
  svg: {
    inline: {
      svgo: {}
    }
  }
}
```
@sam3d @mrleblanc101 What are your thoughts on that?

**Comment by mrleblanc101** [comment]
I'll go with `vueSvgLoader` since that's the name of the underlying package.
I'll update the PR tonight
```
{
  svg: {
    vueSvgLoader: {
      svgo: {}
    }
  }
}
```

**Comment by mrleblanc101** [comment]
@manuelodelain I've updated the PR

**Pull request merged**
