### PR TITLE
feat: update installation section on readme

### PR DESCRIPTION
**Pull request by pablosirera**
I added the same thing that's in the npm readme.

### CODE REVIEW

**Comment by mickaelchanrion** [comment]
For this module, you are actually supposed to use `buildModules`. The documentation on npm seems outdated.
Please note this recent change: #49

**Comment by pablosirera** [comment]
I use `buildModules` and it's works 🤔  maybe should change to `modules` ?

**Comment by kgnfth** [comment]
> I use `buildModules` and it's works 🤔 maybe should change to `modules` ?

same here

**Comment by manuelodelain** [comment]
Hi @pablosirera ! Thanks for the PR but the npm readme is outdated and will be fixed soon with a new package version.

**Pull request closed without merging**
