### PR TITLE
SVGO options

### PR DESCRIPTION
**Pull request by suhodolskiy**

### CODE REVIEW

**Comment by brhx** [comment]
Thanks for the PR! Will give it a look over either later this evening or tomorrow

**Comment by brhx** [comment]
Cool! I've had a look over your PR and thank you for your contribution. Within the next few days I am actually releasing a new version of `nuxt-svg` that allows to both pass any loader options you want to any of the loaders, as well as being able to change their resource query values.

This will hopefully bring it more inline with its [vue counterpart](https://github.com/sam3d/vue-svg), and provide the feature that you want.

**Comment by sam3d** [comment]
This feature has now been released in [`v0.2.0`](https://github.com/sam3d/nuxt-svg/releases/tag/v0.2.0).

**Comment by smhmd** [comment]
@sam3d What's the status on this?

**Comment by webmaster-zundux** [comment]
> Cool! I've had a look over your PR and thank you for your contribution. Within the next few days I am actually releasing a new version of `nuxt-svg` that allows to both pass any loader options you want to any of the loaders, as well as being able to change their resource query values.
> 
> This will hopefully bring it more inline with its [vue counterpart](https://github.com/sam3d/vue-svg), and provide the feature that you want.

@sam3d Please, add an example how to use it in readme.md

**Pull request closed without merging**
